// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_InfoLog_Context
#define _H_InfoLog_Context

static const JUtf8Byte* kContextMenuStr =
"* %i __CompareWithEdited::InfoLog"
"|* %i __CompareWithCurrent::InfoLog"
"|* %i __CompareWithPrevious::InfoLog %l"
"|* %i __Details::InfoLog %l"
"|* %i __BrowseThisRevision::InfoLog"
;

enum {
	kDiffEditedSelectedFilesCtxCmd=1,
	kDiffCurrentSelectedFilesCtxCmd,
	kDiffPrevSelectedFilesCtxCmd,
	kCommitDetailsCtxCmd,
	kBrowseRepoRevisionCtxCmd,
};


inline void ConfigureContextMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
