// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_InfoLog_Context_enum
#define _H_InfoLog_Context_enum

enum {
	kDiffEditedSelectedFilesCtxCmd=1,
	kDiffCurrentSelectedFilesCtxCmd,
	kDiffPrevSelectedFilesCtxCmd,
	kCommitDetailsCtxCmd,
	kBrowseRepoRevisionCtxCmd,
};

#endif
