// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ListBase_Context
#define _H_ListBase_Context

static const JUtf8Byte* kContextMenuStr =
"* %i __CompareWithEdited::ListBase"
"|* %i __CompareWithCurrent::ListBase"
"|* %i __CompareWithPrevious::ListBase %l"
"|* %i __InfoLog::ListBase"
"|* %i __Properties::ListBase %l"
"|* %i __Ignore::ListBase %l"
"|* %i __ShowInFileManager::ListBase"
;

#include "ListBase-Context-enum.h"

#ifndef _H_svn_info_log
#define _H_svn_info_log
#include "svn_info_log.xpm"
#endif

static void ConfigureContextMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kInfoLogSelectedFilesCtxCmd + offset, svn_info_log);
};

#endif
