// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Info_enum
#define _H_MainDirector_Info_enum

enum {
	kInfoLogSelectedFilesCmd=1,
	kPropSelectedFilesCmd,
	kDiffEditedSelectedFilesCmd,
	kDiffCurrentSelectedFilesCmd,
	kDiffPrevSelectedFilesCmd,
	kCommitDetailsCmd,
	kBrowseRepoRevisionCmd,
	kBrowseSelectedRepoRevisionCmd,
};

#endif
