// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Info
#define _H_MainDirector_Info

static const JUtf8Byte* kInfoMenuStr =
"* %i InfoLogSelectedFiles::SVNMainDirector"
"|* %i PropSelectedFiles::SVNMainDirector %l"
"|* %i DiffEditedSelectedFiles::SVNMainDirector"
"|* %i DiffCurrentSelectedFiles::SVNMainDirector"
"|* %i DiffPrevSelectedFiles::SVNMainDirector %l"
"|* %i CommitDetails::SVNMainDirector %l"
"|* %i BrowseRevision::SVNMainDirector"
"|* %i BrowseSelectedRevision::SVNMainDirector"
;

#include "MainDirector-Info-enum.h"

#ifndef _H_svn_info_log
#define _H_svn_info_log
#include "svn_info_log.xpm"
#endif

static void ConfigureInfoMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#i");
	}
	menu->SetItemImage(kInfoLogSelectedFilesCmd + offset, svn_info_log);
};

#endif
