// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Actions_enum
#define _H_MainDirector_Actions_enum

enum {
	kRefreshCmd=1,
	kCloseTabCmd,
	kUpdateWorkingCopyCmd,
	kCleanUpWorkingCopyCmd,
	kAddSelectedFilesCmd,
	kRemoveSelectedFilesCmd,
	kForceRemoveSelectedFilesCmd,
	kResolveSelectedConflictsCmd,
	kCommitSelectedChangesCmd,
	kCommitAllChangesCmd,
	kRevertSelectedChangesCmd,
	kRevertAllChangesCmd,
	kCreateDirectoryCmd,
	kDuplicateSelectedItemCmd,
	kCreatePropertyCmd,
	kRemoveSelectedPropertiesCmd,
	kIgnoreSelectionCmd,
};

#endif
