// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Help
#define _H_MainDirector_Help

static const JUtf8Byte* kHelpMenuStr =
"* %i __About::MainDirector %l"
"|* %i HelpTOC::JX"
"|* %i __Overview::MainDirector"
"|* %i HelpSpecific::JX %l"
"|* %i __Changes::MainDirector"
"|* %i __Credits::MainDirector"
;

#include "MainDirector-Help-enum.h"

#ifndef _H_jx_af_image_jx_jx_help_toc
#define _H_jx_af_image_jx_jx_help_toc
#include <jx-af/image/jx/jx_help_toc.xpm>
#endif
#ifndef _H_jx_af_image_jx_jx_help_specific
#define _H_jx_af_image_jx_jx_help_specific
#include <jx-af/image/jx/jx_help_specific.xpm>
#endif

static void ConfigureHelpMenu(JXTextMenu* menu, const int offset = 0) {
	if (offset == 0 && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts("#h");
	}
	menu->SetItemImage(kTOCCmd + offset, jx_help_toc);
	menu->SetItemImage(kThisWindowCmd + offset, jx_help_specific);
};

#endif
