// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Edit_enum
#define _H_MainDirector_Edit_enum

enum {
	__CopyFullPath=1,
};

#endif
