// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Edit
#define _H_MainDirector_Edit

static const JUtf8Byte* kEditMenuStr =
"* %i CopyFullPath::SVNMainDirector"
;

enum {
	__CopyFullPath=1,
};


static void ConfigureEditMenu(JXTextMenu* menu, const int offset = 0) {
};

#endif
