// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_RepoView_Context
#define _H_RepoView_Context

static const JUtf8Byte* kContextMenuStr =
"* %i __CompareWithEdited::RepoView"
"|* %i __CompareWithCurrent::RepoView"
"|* %i __CompareWithPrevious::RepoView %l"
"|* %i __InfoLog::RepoView"
"|* %i __Properties::RepoView %l"
"|* %i __CheckOut::RepoView %l"
"|* %i __ShowInFileManager::RepoView"
;

#include "RepoView-Context-enum.h"

#ifndef _H_svn_info_log
#define _H_svn_info_log
#include "svn_info_log.xpm"
#endif

static void ConfigureContextMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kInfoLogSelectedFilesCtxCmd + offset, svn_info_log);
};

#endif
