#!/bin/bash

# With no arguments, this script must install from an unpacked tgz.

PRE=$1

BIN=$PRE/usr/bin
DOC=$PRE/usr/share/doc/nps_svn_client
APP=$PRE/usr/share/applications
ICON=$PRE/usr/share/pixmaps

if [[ ! -z $PRE ]]; then
	mkdir -p $BIN $APP $ICON;
fi

install -m755 nps_svn_client $BIN

mkdir -p $DOC
cp README COPYING menu_strings $DOC

cp desktop/nps_svn_client.desktop $APP/
cp desktop/nps_svn_client.xpm     $ICON/
